### PR TITLE
Extract tagging facilities from Shred entity.

### PR DESCRIPTION
**Pull request by xa4a**
* Create new model Shred() that closely represents output of unshred lib, knows nothing about tagging
* Rename old tagging-aware entity to Taggable
* Move shred-specific attributes from Taggable to Shred
* Create an 'object' field in Taggable that stores the Shred. The intention is to later use this to store clusters here, instead of individual shreds.

[Review on Reviewable](https://reviewable.io/reviews/dchaplinsky/unshred-tag/69)

### CODE REVIEW

**Comment by dchaplinsky** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69)



---

That's a bit strange :) You are saying: we need to concentrate on MVP thus should ignore some fruitful ideas. Yet you are adding extra level of complexity to implement your vision of clusters and taggable, while it wasn't discussed, included to MVP, etc.

---

<sup>**[app.py, line 159 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh499XPTU2t1L1RGRts)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/86696a5471cd75a8fc6809bd2b2812c0001d9c52/app.py#L159)):</sup>
2 spaces instead of 4?

---

<sup>**[cli/load_to_mongo.py, line 121 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh47zf2ke_N9Jwh1QFz)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/8441ad9e5fd50d662ded5b4585df2ce7a90daf31/cli/load_to_mongo.py#L121)):</sup>
Why deleted? Or did you delete it from unshred output as well?

---

<sup>**[cli/load_to_mongo.py, line 163 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh49GyadvHKY5K7G1Q0)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/86696a5471cd75a8fc6809bd2b2812c0001d9c52/cli/load_to_mongo.py#L163)):</sup>
Separation of this fields between Shred and Taggable will probably break the efficient get_next_shred requests, as they is relying on that two indexes.

---

<sup>**[fixtures.py, line 1 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh48UbuG8n9PxaVYIjT)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/86696a5471cd75a8fc6809bd2b2812c0001d9c52/fixtures.py#L1)):</sup>
Not used?

---

<sup>**[fixtures.py, line 60 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh49YoVhvsk0bXI9KqN)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/86696a5471cd75a8fc6809bd2b2812c0001d9c52/fixtures.py#L60)):</sup>
_import_from_file won't work here?

---

<sup>**[models/shreds.py, line 84 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh4AKvWmD_YyifQyDAR)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/86696a5471cd75a8fc6809bd2b2812c0001d9c52/models/shreds.py#L84)):</sup>
Please add here:
TODO: randomisation here as well

---

**Comment by xa4a** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69)



---

Please assume this PR to be a discussion of what to include into MVP. I'm open to sugestions. I believe multi-shred clusters will be a must at some point after MVP. While multi-shred clusters are not strictly required for MVP, focusing on the 'pairs' of shreds, while maybe being simpler abstraction, will result in too much techincal debt, i.e enormous refactoring further on to get rid of them.
As for taggables it's as simple as separating the constant/static shred image and data from dynamic user interaction facilities. These are semantically different and storing them in a single model seemed to be a shortcoming. 

---

<sup>**[app.py, line 159 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh499XPTU2t1L1RGRts)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/86696a5471cd75a8fc6809bd2b2812c0001d9c52/app.py#L159)):</sup>
Done.

---

<sup>**[cli/load_to_mongo.py, line 121 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh47zf2ke_N9Jwh1QFz)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/8441ad9e5fd50d662ded5b4585df2ce7a90daf31/cli/load_to_mongo.py#L121)):</sup>
It's not used anywhere in unshred-tag. I believe if you don't del(...) here,it won't be saved in the model as it was not saved previously.

---

<sup>**[cli/load_to_mongo.py, line 163 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh49GyadvHKY5K7G1Q0)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/86696a5471cd75a8fc6809bd2b2812c0001d9c52/cli/load_to_mongo.py#L163)):</sup>
What about: 
* move batch name to features. 
* every taggable (i.e. individual shreds and clusters) has its own set of features, so e.g. a cluster taggable will inherit its 'batch' from its parents. 

---

<sup>**[fixtures.py, line 1 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh48UbuG8n9PxaVYIjT)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/86696a5471cd75a8fc6809bd2b2812c0001d9c52/fixtures.py#L1)):</sup>
Done.

---

<sup>**[fixtures.py, line 60 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh49YoVhvsk0bXI9KqN)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/86696a5471cd75a8fc6809bd2b2812c0001d9c52/fixtures.py#L60)):</sup>
It seems like you can't really deserialize GenericReferenceField

---

<sup>**[models/shreds.py, line 84 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh4AKvWmD_YyifQyDAR)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/86696a5471cd75a8fc6809bd2b2812c0001d9c52/models/shreds.py#L84)):</sup>
Done.

---

**Comment by dchaplinsky** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69)



---

Well, you have a right of experimenting simply because you are writing all the code at that point :)
But I'd be a happier camper if we'll discuss such things before diving into implementation.

On taggable note. Strictly speaking, there was a separation, because tags field were using embeddeddocuments, which is kind of normal in mongo world. Your approach is closer to postgres :) Still ok, but as I said above, I'd rather discuss it before laying down some code

---

<sup>**[cli/load_to_mongo.py, line 121 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh47zf2ke_N9Jwh1QFz)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/8441ad9e5fd50d662ded5b4585df2ce7a90daf31/cli/load_to_mongo.py#L121)):</sup>
Hmm, yes, you are right. For some reason I was thinking that fields denoted in the model is just a declaration, yet, you can stuff everything you want when doing Shred(foo="bar") etc.

---

<sup>**[cli/load_to_mongo.py, line 163 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh49GyadvHKY5K7G1Q0)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/86696a5471cd75a8fc6809bd2b2812c0001d9c52/cli/load_to_mongo.py#L163)):</sup>
Ok, but then sheet should also go there.
Also, probably it's not features (which is kind of computed) but meta or something.

---

<sup>**[fixtures.py, line 59 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh49YoVhvsk0bXI9KqN)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/86696a5471cd75a8fc6809bd2b2812c0001d9c52/fixtures.py#L59)):</sup>
Ideally I'd like to see minor extension to _import_from_file routine, optional callback that will be applied to a record.
Or a dict that will have {"fieldname": callable, ...} so you can use lambda's to pre-process the data.

Clearly it's better than read raw file and parse it and repeat yourself.

---

**Comment by xa4a** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69)



---

As discussed in slack: Shred is now EmbeddedField inside Taggable, batch is at Taggable level. PTAL

---

<sup>**[cli/load_to_mongo.py, line 163 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh49GyadvHKY5K7G1Q0)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/86696a5471cd75a8fc6809bd2b2812c0001d9c52/cli/load_to_mongo.py#L163)):</sup>
This is reverted.

---

<sup>**[fixtures.py, line 59 \[r1\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Jh49YoVhvsk0bXI9KqN)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/86696a5471cd75a8fc6809bd2b2812c0001d9c52/fixtures.py#L59)):</sup>
As discussed, Shred is a field within Taggable. _import_from_file works fine.

---

**Comment by dchaplinsky** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69)



---

Everything is perfect except one misc comment below. Happy to merge.

---

<sup>**[models/shreds.py, line 62 \[r3\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Ji-EwOOLIkg5VzYwEnD)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/c7998913981b7a7932c819c104c7b9b2e71dbdda/models/shreds.py#L62)):</sup>
That looks wrong now as we don't have Batches model anymore.

---

**Comment by xa4a** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69)







---

<sup>**[models/shreds.py, line 62 \[r3\]](https://reviewable.io:443/reviews/dchaplinsky/unshred-tag/69#-Ji-EwOOLIkg5VzYwEnD)** ([raw file](https://github.com/dchaplinsky/unshred-tag/blob/c7998913981b7a7932c819c104c7b9b2e71dbdda/models/shreds.py#L62)):</sup>
Now the batch-removing branch merged.

---

**Pull request merged**
